import {
  Button,
  Divider,
  Group,
  PasswordInput,
  Stack,
  Switch,
  TextInput,
  Textarea,
} from "@mantine/core";
import { useForm } from "@mantine/form";
import { IconKey, IconShieldCheck, IconUser } from "@tabler/icons-react";

import type {
  CreateStaticDatabaseUserRequest,
  DatabaseInfoItem,
  DatabaseServerInfoItem,
  DatabaseServerPrivilegeInfo,
  GetStaticDatabaseUserDetailResponse,
  UpdateStaticDatabaseUserRequest,
} from "@/api/types";
import { FormSection } from "@/components/common/FormSection";

import { PrivilegesEditor } from "./PrivilegesEditor";

interface StaticUserFormValues {
  UserPassword: string;
  GenerateNewPassword: boolean;
  Description: string;
  Servers: DatabaseServerPrivilegeInfo[];
}

interface StaticUserFormProps {
  servers: DatabaseServerInfoItem[];
  databases: DatabaseInfoItem[];
  initial?: GetStaticDatabaseUserDetailResponse;
  initialServers?: DatabaseServerPrivilegeInfo[];
  submitLabel: string;
  onCancel: () => void;
  onSubmit: (
    payload: CreateStaticDatabaseUserRequest | UpdateStaticDatabaseUserRequest,
  ) => Promise<void> | void;
  submitting?: boolean;
}

export function StaticUserForm({
  servers,
  databases,
  initial,
  initialServers,
  submitLabel,
  onCancel,
  onSubmit,
  submitting,
}: StaticUserFormProps) {
  const isEdit = Boolean(initial);

  const form = useForm<StaticUserFormValues>({
    initialValues: {
      UserPassword: "",
      GenerateNewPassword: false,
      Description: initial?.Description ?? "",
      Servers: initialServers ?? [],
    },
    validate: {
      UserPassword: (v, all) => {
        if (isEdit) return null;
        if (all.GenerateNewPassword) return null;
        return v.length < 12
          ? "Password must be at least 12 characters (or generate one)"
          : null;
      },
    },
  });

  const submit = form.onSubmit(async (values) => {
    if (isEdit && initial) {
      const payload: UpdateStaticDatabaseUserRequest = {
        Id: initial.Id,
        UserName: initial.UserName,
        GenerateNewPassword: values.GenerateNewPassword,
        NewDescription: values.Description.trim() || null,
        Servers: values.Servers,
      };
      await onSubmit(payload);
    } else {
      const payload: CreateStaticDatabaseUserRequest = {
        UserPassword: values.GenerateNewPassword ? "" : values.UserPassword,
        Description: values.Description.trim() || null,
        Servers: values.Servers,
      };
      await onSubmit(payload);
    }
  });

  return (
    <form onSubmit={submit} noValidate>
      <Stack gap="lg">
        <FormSection
          title="Identity"
          description={
            isEdit
              ? "The username is assigned by the portal and cannot be changed."
              : "A free-form description shown in the operator UI."
          }
          icon={IconUser}
        >
          {isEdit && initial && (
            <TextInput
              label="Username"
              value={initial.UserName}
              disabled
              styles={{
                input: { fontFamily: "var(--mantine-font-family-monospace)" },
              }}
            />
          )}
          <Textarea
            label="Description"
            placeholder="Read-replica polling for analytics"
            autosize
            minRows={2}
            {...form.getInputProps("Description")}
          />
        </FormSection>

        <Divider />

        <FormSection
          title="Password"
          description={
            isEdit
              ? "Optionally rotate this user's password — the new value is returned in the response."
              : "Either supply a strong password or have the server generate one for you."
          }
          icon={IconKey}
        >
          <Switch
            label={
              isEdit ? "Rotate password on save" : "Generate password on the server"
            }
            description={
              isEdit
                ? "If enabled, the user's password will be rotated and returned once."
                : "Recommended — the server generates and returns a strong password."
            }
            checked={form.values.GenerateNewPassword}
            onChange={(e) =>
              form.setFieldValue("GenerateNewPassword", e.currentTarget.checked)
            }
          />
          <PasswordInput
            label={isEdit ? "Password (managed by server)" : "Password"}
            placeholder={
              form.values.GenerateNewPassword ? "Will be generated by server" : ""
            }
            disabled={isEdit || form.values.GenerateNewPassword}
            autoComplete="new-password"
            {...form.getInputProps("UserPassword")}
          />
        </FormSection>

        <Divider />

        <FormSection
          title="Server &amp; database privileges"
          description="Pick the servers, databases, and granular privileges this user should hold."
          icon={IconShieldCheck}
        >
          <PrivilegesEditor
            servers={servers}
            databases={databases}
            value={form.values.Servers}
            onChange={(next) => form.setFieldValue("Servers", next)}
          />
        </FormSection>

        <Group justify="flex-end" mt="sm">
          <Button variant="default" onClick={onCancel} disabled={submitting}>
            Cancel
          </Button>
          <Button type="submit" loading={submitting}>
            {submitLabel}
          </Button>
        </Group>
      </Stack>
    </form>
  );
}
